production:
  solr:
    hostname: localhost
    port: 8080 #tomcat defaults to port 8080
    path: /solr
    log_level: WARNING
    solr_home: solr

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development
    solr_home: solr

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
