source 'https://rubygems.org'

ruby '2.2.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.2'
# Use postgresql as the database for Active Record
gem 'pg'
# Use Devise for user authentication
gem 'devise'
# Use Sunspot for search
gem 'sunspot_rails'
gem 'sunspot_solr'
# Contact form
gem 'mail_form'
# User Figaro for ENV variables
gem 'figaro'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use bourbon for front end
gem 'bourbon'
gem 'neat'
gem 'bitters'
gem 'refills'
gem 'normalize-rails'
gem 'jquery-ui-rails'

# Use Kaminar for pagination
gem 'kaminari'

# Sprig to seed db
gem 'sprig'

# Rails Admin for administration
gem 'rails_admin'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

#Rollbar for error tracking
gem 'rollbar'
gem 'oj' 

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :production do
	gem 'unicorn'
end	

group :development do
	gem 'better_errors'
	gem 'letter_opener'
end
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'dotenv-rails'
end

group :test do
	gem 'minitest-reporters', '1.0.5'
	gem 'minitest-around'
	gem 'mini_backtrace', '0.1.3'
	gem 'guard-minitest', '2.3.1'
	gem 'factory_girl_rails'
	gem 'capybara'
	gem 'ffaker'
	gem 'database_cleaner'
	gem 'simplecov'
end

